### ISSUE TITLE
[activerecord] Implement ActiveRecord$Base methods

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/rue#49]
### Summary

The remaining methods to be implemented are as follows

```
- [x] ActiveRecord::Core
- [x] ActiveRecord::Persistence
- [ ] ActiveRecord::ReadonlyAttributes
- [ ] ActiveRecord::ModelSchema
- [ ] ActiveRecord::Inheritance
- [x] ActiveRecord::Scoping
- [ ] ActiveRecord::Sanitization
- [ ] ActiveRecord::AttributeAssignment
- [x] ActiveModel::Conversion
- [ ] ActiveRecord::Integration
- [ ] ActiveRecord::Validations
- [ ] ActiveRecord::CounterCache
- [ ] ActiveRecord::Attributes
- [ ] ActiveRecord::Locking::Optimistic (because javascript single thread)
- [ ] ActiveRecord::Locking::Pessimistic
- [x] ActiveRecord::AttributeMethods
- [x] ActiveRecord::Callbacks
- [ ] ActiveRecord::Timestamp
- [x] ActiveRecord::Associations
- [ ] ActiveModel::SecurePassword
- [x] ActiveRecord::AutosaveAssociation
- [ ] ActiveRecord::NestedAttributes
- [ ] ActiveRecord::Transactions
- [x] ActiveRecord::NoTouching
- [x] ActiveRecord::Reflection
- [ ] ActiveRecord::AttributeMethods::Serialization
- [x] ActiveRecord::Store
- [ ] ActiveRecord::SecureToken
- [ ] ActiveRecord::SignedId
- [ ] ActiveRecord::Suppressor
- [x] ActiveRecord::Quering (nodoc)
```
