### ISSUE TITLE
[activesupport] Implement ActiveSupport$Base methods

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/rue#51]
### Summary

The remaining methods to be implemented are as follows.

```
- [ ] MODULE ActiveSupport::ActionableError
- [ ] MODULE ActiveSupport::Autoload
- [ ] MODULE ActiveSupport::Benchmarkable
- [ ] MODULE ActiveSupport::Cache
- [ ] MODULE ActiveSupport::Callbacks
- [ ] MODULE ActiveSupport::CompareWithRange
- [ ] MODULE ActiveSupport::Concern
- [ ] MODULE ActiveSupport::Concurrency
- [ ] MODULE ActiveSupport::Configurable
- [ ] MODULE ActiveSupport::Dependencies
- [x] MODULE ActiveSupport::DescendantsTracker
- [ ] MODULE ActiveSupport::ForkTracker
- [ ] MODULE ActiveSupport::Gzip
- [ ] MODULE ActiveSupport::Inflector
- [ ] MODULE ActiveSupport::JSON
- [ ] MODULE ActiveSupport::LazyLoadHooks
- [ ] MODULE ActiveSupport::LoggerSilence
- [ ] MODULE ActiveSupport::Messages
- [ ] MODULE ActiveSupport::Multibyte
- [ ] MODULE ActiveSupport::Notifications
- [ ] MODULE ActiveSupport::NumberHelper
- [ ] MODULE ActiveSupport::NumericWithFormat
- [ ] MODULE ActiveSupport::PerThreadRegistry
- [ ] MODULE ActiveSupport::RangeWithFormat
- [ ] MODULE ActiveSupport::Rescuable
- [ ] MODULE ActiveSupport::SecurityUtils
- [ ] MODULE ActiveSupport::TaggedLogging
- [ ] MODULE ActiveSupport::Testing
- [ ] MODULE ActiveSupport::VERSION
- [ ] MODULE ActiveSupport::XmlMini
- [ ] MODULE ActiveSupport::XmlMini_LibXMLSAX
- [ ] MODULE ActiveSupport::XmlMini_NokogiriSAX
- [ ] CLASS ActiveSupport::ArrayInquirer
- [ ] CLASS ActiveSupport::BacktraceCleaner
- [ ] CLASS ActiveSupport::CachingKeyGenerator
- [ ] CLASS ActiveSupport::ConfigurationFile
- [ ] CLASS ActiveSupport::CurrentAttributes
- [x] CLASS ActiveSupport::Deprecation
- [x] CLASS ActiveSupport::DeprecationException
- [ ] CLASS ActiveSupport::Duration
- [ ] CLASS ActiveSupport::EncryptedConfiguration
- [ ] CLASS ActiveSupport::EncryptedFile
- [ ] CLASS ActiveSupport::EventedFileUpdateChecker
- [ ] CLASS ActiveSupport::ExecutionWrapper
- [ ] CLASS ActiveSupport::Executor
- [ ] CLASS ActiveSupport::FileUpdateChecker
- [ ] CLASS ActiveSupport::HashWithIndifferentAccess
- [ ] CLASS ActiveSupport::InheritableOptions
- [ ] CLASS ActiveSupport::KeyGenerator
- [ ] CLASS ActiveSupport::LogSubscriber
- [ ] CLASS ActiveSupport::Logger
- [ ] CLASS ActiveSupport::MessageEncryptor
- [ ] CLASS ActiveSupport::MessageVerifier
- [ ] CLASS ActiveSupport::OrderedHash
- [ ] CLASS ActiveSupport::OrderedOptions
- [ ] CLASS ActiveSupport::ParameterFilter
- [ ] CLASS ActiveSupport::ProxyObject
- [ ] CLASS ActiveSupport::Reloader
- [ ] CLASS ActiveSupport::SafeBuffer
- [ ] CLASS ActiveSupport::SecureCompareRotator
- [ ] CLASS ActiveSupport::StringInquirer
- [ ] CLASS ActiveSupport::Subscriber
- [ ] CLASS ActiveSupport::TestCase
- [ ] CLASS ActiveSupport::TimeWithZone
- [ ] CLASS ActiveSupport::TimeZone
- [ ] CLASS ActiveSupport::XMLConverter
```
